"""remove_company_description_and_sector_from_prediction_and_add_description_to_profile

Revision ID: 0d3fa7d9ca76
Revises: a87ea9fce36f
Create Date: 2026-07-11 13:34:31.609496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d3fa7d9ca76'
down_revision: Union[str, Sequence[str], None] = 'a87ea9fce36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profile', sa.Column('company_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('prediction', sa.Column('likely_guidance', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.drop_column('prediction', 'sector')
    op.drop_column('prediction', 'company_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('company_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('prediction', sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('prediction', 'likely_guidance')
    op.drop_column('company_profile', 'company_description')
    # ### end Alembic commands ###
