"""Initial commit to postgres

Revision ID: 1753aaffad92
Revises: 
Create Date: 2026-04-06 17:38:51.781757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1753aaffad92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_clerk_id'), 'user', ['clerk_id'], unique=True)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expected_price_move', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('move_vs_implied', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guidance_expectation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bull_factors', sa.JSON(), nullable=True),
    sa.Column('bear_factors', sa.JSON(), nullable=True),
    sa.Column('debate_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_ticker'), 'prediction', ['ticker'], unique=False)
    op.create_table('predictionchat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictionchat_ticker'), 'predictionchat', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictionchat_ticker'), table_name='predictionchat')
    op.drop_table('predictionchat')
    op.drop_index(op.f('ix_prediction_ticker'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_user_clerk_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
