"""add_provenance_to_earnings_history

Revision ID: 2dc31ab0adf3
Revises: a461db4b85d3
Create Date: 2026-07-07 12:29:26.643086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc31ab0adf3'
down_revision: Union[str, Sequence[str], None] = 'a461db4b85d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings_history', sa.Column('provenance', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earnings_history', 'provenance')
    # ### end Alembic commands ###
