"""Add ResearchThesis table

Revision ID: 3197622d2454
Revises: fb2f31ccf80f
Create Date: 2026-08-07 19:39:10.858659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3197622d2454'
down_revision: Union[str, Sequence[str], None] = 'fb2f31ccf80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_thesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('source_trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headline_view', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('business_viability_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('competitive_landscape_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('macro_context_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bull_case', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bear_case', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('catalysts', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('evidence_table', sa.JSON(), nullable=True),
    sa.Column('what_changed_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disclaimer_shown', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_thesis_ticker'), 'research_thesis', ['ticker'], unique=False)
    op.create_index(op.f('ix_research_thesis_user_id'), 'research_thesis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_thesis_user_id'), table_name='research_thesis')
    op.drop_index(op.f('ix_research_thesis_ticker'), table_name='research_thesis')
    op.drop_table('research_thesis')
    # ### end Alembic commands ###
