"""add_company_description

Revision ID: 670a06f4212d
Revises: 2dc31ab0adf3
Create Date: 2026-07-08 06:09:18.649534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '670a06f4212d'
down_revision: Union[str, Sequence[str], None] = '2dc31ab0adf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('company_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction', 'company_description')
    # ### end Alembic commands ###
