"""add earnings enrichment tables

Revision ID: a461db4b85d3
Revises: 0acfc5647feb
Create Date: 2026-07-05 09:11:31.904192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a461db4b85d3'
down_revision: Union[str, Sequence[str], None] = '0acfc5647feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profile',
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outstanding_shares', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('earnings_calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('num_estimates', sa.Integer(), nullable=True),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'report_date', name='uq_cal_ticker_date')
    )
    op.create_index(op.f('ix_earnings_calendar_event_report_date'), 'earnings_calendar_event', ['report_date'], unique=False)
    op.create_index(op.f('ix_earnings_calendar_event_ticker'), 'earnings_calendar_event', ['ticker'], unique=False)
    op.create_table('earnings_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fiscal_quarter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('eps_actual', sa.Float(), nullable=True),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('eps_surprise_pct', sa.Float(), nullable=True),
    sa.Column('eps_yoy', sa.Float(), nullable=True),
    sa.Column('eps_beat', sa.Boolean(), nullable=True),
    sa.Column('revenue_actual', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_surprise_pct', sa.Float(), nullable=True),
    sa.Column('revenue_yoy', sa.Float(), nullable=True),
    sa.Column('revenue_beat', sa.Boolean(), nullable=True),
    sa.Column('reaction_1d_pct', sa.Float(), nullable=True),
    sa.Column('reaction_5d_pct', sa.Float(), nullable=True),
    sa.Column('reaction_volume', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'report_date', name='uq_hist_ticker_date')
    )
    op.create_index(op.f('ix_earnings_history_report_date'), 'earnings_history', ['report_date'], unique=False)
    op.create_index(op.f('ix_earnings_history_ticker'), 'earnings_history', ['ticker'], unique=False)
    op.alter_column('prediction', 'rebuttal_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('prediction', 'actual_direction',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prediction', 'actual_direction',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('prediction', 'rebuttal_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_earnings_history_ticker'), table_name='earnings_history')
    op.drop_index(op.f('ix_earnings_history_report_date'), table_name='earnings_history')
    op.drop_table('earnings_history')
    op.drop_index(op.f('ix_earnings_calendar_event_ticker'), table_name='earnings_calendar_event')
    op.drop_index(op.f('ix_earnings_calendar_event_report_date'), table_name='earnings_calendar_event')
    op.drop_table('earnings_calendar_event')
    op.drop_table('company_profile')
    # ### end Alembic commands ###
